"""Mass and power budget: planned vs measured, margins, and a markdown snapshot."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .config import MAX_TAKEOFF_MASS_G, TARGET_TAKEOFF_MASS_G, Design
from .mass import total_mass_g


@dataclass
class PowerSummary:
    """Totals and battery checks derived from the power items."""

    typical_w: float
    peak_w: float
    peak_current_a: float
    max_current_a: float  # battery capacity x C rating
    endurance_min: float  # usable energy / typical draw


def power_summary(d: Design) -> PowerSummary:
    typical = sum(p.typical_w for p in d.power_items)
    peak = sum(p.peak_w for p in d.power_items)
    capacity_ah = d.battery_wh / d.battery_nominal_v
    return PowerSummary(
        typical_w=typical,
        peak_w=peak,
        peak_current_a=peak / d.battery_nominal_v,
        max_current_a=capacity_ah * d.battery_c_rating,
        endurance_min=d.battery_wh * d.battery_usable_fraction / typical * 60,
    )


def mass_markdown(d: Design) -> str:
    planned = sum(c.mass_g for c in d.components)
    actual = total_mass_g(d)
    weighed = sum(c.measured_g is not None for c in d.components)
    lines = [
        "| Component | Planned [g] | Measured [g] | Delta [g] | Note |",
        "|---|---:|---:|---:|---|",
    ]
    for c in sorted(d.components, key=lambda c: -c.actual_g):
        meas = "" if c.measured_g is None else f"{c.measured_g:.1f}"
        delta = "" if c.measured_g is None else f"{c.measured_g - c.mass_g:+.1f}"
        lines.append(f"| {c.name} | {c.mass_g:.1f} | {meas} | {delta} | {c.note} |")
    lines.append(f"| **Total** | **{planned:.1f}** | **{actual:.1f}** | |")
    lines += [
        "",
        f"- Weighed: {weighed} of {len(d.components)} components "
        "(unweighed parts use the planned value in the total)",
        f"- Margin to target ({TARGET_TAKEOFF_MASS_G:.0f} g): "
        f"{TARGET_TAKEOFF_MASS_G - actual:+.1f} g",
        f"- Margin to legal limit ({MAX_TAKEOFF_MASS_G:.0f} g): "
        f"{MAX_TAKEOFF_MASS_G - actual:+.1f} g",
    ]
    return "\n".join(lines)


def power_markdown(d: Design) -> str:
    s = power_summary(d)
    lines = [
        "| Load | Typical [W] | Peak [W] | Note |",
        "|---|---:|---:|---|",
    ]
    for p in sorted(d.power_items, key=lambda p: -p.peak_w):
        lines.append(f"| {p.name} | {p.typical_w:.2f} | {p.peak_w:.2f} | {p.note} |")
    lines.append(f"| **Total** | **{s.typical_w:.2f}** | **{s.peak_w:.2f}** | |")
    lines += [
        "",
        f"- Battery: {d.battery_wh:.2f} Wh at {d.battery_nominal_v:.1f} V, "
        f"{d.battery_usable_fraction * 100:.0f} % usable",
        f"- Peak current {s.peak_current_a:.1f} A vs {s.max_current_a:.1f} A "
        f"battery limit ({d.battery_c_rating:.0f}C): "
        f"{'OK' if s.peak_current_a <= s.max_current_a else 'OVER LIMIT'}",
        f"- Endurance at typical draw: {s.endurance_min:.1f} min "
        "(ideal; see `task analyze` for the real-world factor)",
    ]
    return "\n".join(lines)


def write_markdown(d: Design, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# Mass and power budget\n\n"
        "Generated by `task budget` from `src/planedesign/config.py`. "
        "Edit the config, not this file.\n\n"
        "## Mass\n\n" + mass_markdown(d) + "\n\n## Power\n\n" + power_markdown(d) + "\n"
    )
    return path
